main: com.gmail.andrew.miner3.plugins.Paintball.PluginManager
name: Paintball
version: 0.1
author: SmokyMiner
description: Robust Paintball Minigame
commands:
  join:
    description: Join a piantball lobby
    usage: "/join [lobby #]"
  all:
    description: Send message in all chat to both teams
    usage: /all msg
  pb:
    description: Paintball Command Prefix
    usage: /pb [command]