main: SmokyMiner.Examples.Paintball.PaintballPlugin
name: Paintball
version: 0.2
author: SmokyMiner
description: Robust Paintball Minigame
api-version: 1.13
commands:
  join:
    description: Join a piantball lobby
    usage: "/join [lobby #]"
  all:
    description: Send message in all chat to both teams
    usage: /all msg
  pb:
    description: Paintball Command Prefix
    usage: /pb [command]